/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class adminPage extends javax.swing.JFrame {

    /**
     * Creates new form adminPage
     */
    public adminPage() {
        initComponents();
        DashboardPanel.setVisible(true);
        NoticePanel.setVisible(false);
        CalenderPanel.setVisible(false);
        DeptMsPanel.setVisible(false);
        StudentMsPanel.setVisible(false);
        AddTeacherPanel.setVisible(false);
        FinancePanel.setVisible(false);
        jPanel4.setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        btnDashBoard1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnNotice1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCalender1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnDept1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnStudent1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnTeacher1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btnFinance1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        DashboardPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NoticePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CalenderPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DeptMsPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        StudentMsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        AddTeacherPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        FinancePanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Page");
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(104, 45));

        btnDashBoard1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDashBoard1.setForeground(new java.awt.Color(51, 51, 51));
        btnDashBoard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDashBoard1.setText("Dashboard");
        btnDashBoard1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashBoard1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDashBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDashBoard1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(104, 45));

        btnNotice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNotice1.setForeground(new java.awt.Color(51, 51, 51));
        btnNotice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnNotice1.setText("Notice ");
        btnNotice1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNotice1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNotice1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNotice1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(104, 45));

        btnCalender1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalender1.setForeground(new java.awt.Color(51, 51, 51));
        btnCalender1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCalender1.setText("Calender");
        btnCalender1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCalender1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalender1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalender1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(104, 45));

        btnDept1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDept1.setForeground(new java.awt.Color(51, 51, 51));
        btnDept1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDept1.setText("Depertment");
        btnDept1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDept1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(btnDept1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDept1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(104, 45));

        btnStudent1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStudent1.setForeground(new java.awt.Color(51, 51, 51));
        btnStudent1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnStudent1.setText("Student Ms");
        btnStudent1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStudent1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStudent1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(104, 45));

        btnTeacher1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTeacher1.setForeground(new java.awt.Color(51, 51, 51));
        btnTeacher1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTeacher1.setText("Teacher Ms");
        btnTeacher1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTeacher1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTeacher1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTeacher1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));

        btnFinance1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFinance1.setForeground(new java.awt.Color(51, 51, 51));
        btnFinance1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFinance1.setText("Finance ");
        btnFinance1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinance1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinance1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));

        DashboardPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DashBoard");

        javax.swing.GroupLayout DashboardPanelLayout = new javax.swing.GroupLayout(DashboardPanel);
        DashboardPanel.setLayout(DashboardPanelLayout);
        DashboardPanelLayout.setHorizontalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 521, Short.MAX_VALUE))
        );
        DashboardPanelLayout.setVerticalGroup(
            DashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 535, Short.MAX_VALUE))
        );

        jPanel1.add(DashboardPanel);

        NoticePanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Notice");

        javax.swing.GroupLayout NoticePanelLayout = new javax.swing.GroupLayout(NoticePanel);
        NoticePanel.setLayout(NoticePanelLayout);
        NoticePanelLayout.setHorizontalGroup(
            NoticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoticePanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 521, Short.MAX_VALUE))
        );
        NoticePanelLayout.setVerticalGroup(
            NoticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NoticePanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 535, Short.MAX_VALUE))
        );

        jPanel1.add(NoticePanel);

        CalenderPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel4.setText("Academic Calender");

        javax.swing.GroupLayout CalenderPanelLayout = new javax.swing.GroupLayout(CalenderPanel);
        CalenderPanel.setLayout(CalenderPanelLayout);
        CalenderPanelLayout.setHorizontalGroup(
            CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalenderPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 553, Short.MAX_VALUE))
        );
        CalenderPanelLayout.setVerticalGroup(
            CalenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalenderPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 538, Short.MAX_VALUE))
        );

        jPanel1.add(CalenderPanel);

        DeptMsPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel5.setText("Dept Ms Panel");

        javax.swing.GroupLayout DeptMsPanelLayout = new javax.swing.GroupLayout(DeptMsPanel);
        DeptMsPanel.setLayout(DeptMsPanelLayout);
        DeptMsPanelLayout.setHorizontalGroup(
            DeptMsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeptMsPanelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 544, Short.MAX_VALUE))
        );
        DeptMsPanelLayout.setVerticalGroup(
            DeptMsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeptMsPanelLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 526, Short.MAX_VALUE))
        );

        jPanel1.add(DeptMsPanel);

        StudentMsPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel8.setText("Student Panel");

        javax.swing.GroupLayout StudentMsPanelLayout = new javax.swing.GroupLayout(StudentMsPanel);
        StudentMsPanel.setLayout(StudentMsPanelLayout);
        StudentMsPanelLayout.setHorizontalGroup(
            StudentMsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentMsPanelLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 488, Short.MAX_VALUE))
        );
        StudentMsPanelLayout.setVerticalGroup(
            StudentMsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentMsPanelLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 509, Short.MAX_VALUE))
        );

        jPanel1.add(StudentMsPanel);

        AddTeacherPanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel6.setText("Add teacher");

        javax.swing.GroupLayout AddTeacherPanelLayout = new javax.swing.GroupLayout(AddTeacherPanel);
        AddTeacherPanel.setLayout(AddTeacherPanelLayout);
        AddTeacherPanelLayout.setHorizontalGroup(
            AddTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTeacherPanelLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 540, Short.MAX_VALUE))
        );
        AddTeacherPanelLayout.setVerticalGroup(
            AddTeacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTeacherPanelLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 523, Short.MAX_VALUE))
        );

        jPanel1.add(AddTeacherPanel);

        FinancePanel.setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel7.setText("Finance");

        javax.swing.GroupLayout FinancePanelLayout = new javax.swing.GroupLayout(FinancePanel);
        FinancePanel.setLayout(FinancePanelLayout);
        FinancePanelLayout.setHorizontalGroup(
            FinancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinancePanelLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 515, Short.MAX_VALUE))
        );
        FinancePanelLayout.setVerticalGroup(
            FinancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FinancePanelLayout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 513, Short.MAX_VALUE))
        );

        jPanel1.add(FinancePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDashBoard1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashBoard1MouseClicked
        // TODO add your handling code here:
        DashboardPanel.setVisible(true);
        NoticePanel.setVisible(false);
        CalenderPanel.setVisible(false);
        DeptMsPanel.setVisible(false);
        StudentMsPanel.setVisible(false);
        AddTeacherPanel.setVisible(false);
        FinancePanel.setVisible(false);

        jPanel4.setBackground(Color.white);

        Color lightBlue = new Color(204, 204, 255);
        jPanel5.setBackground(lightBlue);
        jPanel6.setBackground(lightBlue);
        jPanel7.setBackground(lightBlue);
        jPanel8.setBackground(lightBlue);
        jPanel9.setBackground(lightBlue);
        jPanel10.setBackground(lightBlue);


    }//GEN-LAST:event_btnDashBoard1MouseClicked

    private void btnNotice1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNotice1MouseClicked
        // TODO add your handling code here:
        DashboardPanel.setVisible(false);
        NoticePanel.setVisible(true);
        CalenderPanel.setVisible(false);
        DeptMsPanel.setVisible(false);
        StudentMsPanel.setVisible(false);
        AddTeacherPanel.setVisible(false);
        FinancePanel.setVisible(false);

        jPanel5.setBackground(Color.white);

        Color lightBlue = new Color(204, 204, 255);
        jPanel4.setBackground(lightBlue);
        jPanel6.setBackground(lightBlue);
        jPanel7.setBackground(lightBlue);
        jPanel8.setBackground(lightBlue);
        jPanel9.setBackground(lightBlue);
        jPanel10.setBackground(lightBlue);
    }//GEN-LAST:event_btnNotice1MouseClicked

    private void btnCalender1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCalender1MouseClicked
        // TODO add your handling code here:
        DashboardPanel.setVisible(false);
        NoticePanel.setVisible(false);
        CalenderPanel.setVisible(true);
        DeptMsPanel.setVisible(false);
        StudentMsPanel.setVisible(false);
        AddTeacherPanel.setVisible(false);
        FinancePanel.setVisible(false);

        jPanel6.setBackground(Color.white);

        Color lightBlue = new Color(204, 204, 255);
        jPanel4.setBackground(lightBlue);
        jPanel5.setBackground(lightBlue);
        jPanel7.setBackground(lightBlue);
        jPanel8.setBackground(lightBlue);
        jPanel9.setBackground(lightBlue);
        jPanel10.setBackground(lightBlue);
    }//GEN-LAST:event_btnCalender1MouseClicked

    private void btnDept1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDept1MouseClicked
        // TODO add your handling code here:
        DashboardPanel.setVisible(false);
        NoticePanel.setVisible(false);
        CalenderPanel.setVisible(false);
        DeptMsPanel.setVisible(true);
        StudentMsPanel.setVisible(false);
        AddTeacherPanel.setVisible(false);
        FinancePanel.setVisible(false);

        jPanel7.setBackground(Color.white);

        Color lightBlue = new Color(204, 204, 255);
        jPanel4.setBackground(lightBlue);
        jPanel5.setBackground(lightBlue);
        jPanel6.setBackground(lightBlue);
        jPanel8.setBackground(lightBlue);
        jPanel9.setBackground(lightBlue);
        jPanel10.setBackground(lightBlue);
    }//GEN-LAST:event_btnDept1MouseClicked

    private void btnStudent1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudent1MouseClicked
        // TODO add your handling code here:
        DashboardPanel.setVisible(false);
        NoticePanel.setVisible(false);
        CalenderPanel.setVisible(false);
        DeptMsPanel.setVisible(false);
        StudentMsPanel.setVisible(true);
        AddTeacherPanel.setVisible(false);
        FinancePanel.setVisible(false);

        jPanel8.setBackground(Color.white);

        Color lightBlue = new Color(204, 204, 255);
        jPanel4.setBackground(lightBlue);
        jPanel5.setBackground(lightBlue);
        jPanel6.setBackground(lightBlue);
        jPanel7.setBackground(lightBlue);
        jPanel9.setBackground(lightBlue);
        jPanel10.setBackground(lightBlue);
    }//GEN-LAST:event_btnStudent1MouseClicked

    private void btnTeacher1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTeacher1MouseClicked
        // TODO add your handling code here:
        DashboardPanel.setVisible(false);
        NoticePanel.setVisible(false);
        CalenderPanel.setVisible(false);
        DeptMsPanel.setVisible(false);
        StudentMsPanel.setVisible(false);
        AddTeacherPanel.setVisible(true);
        FinancePanel.setVisible(false);

        jPanel9.setBackground(Color.white);

        Color lightBlue = new Color(204, 204, 255);
        jPanel4.setBackground(lightBlue);
        jPanel5.setBackground(lightBlue);
        jPanel6.setBackground(lightBlue);
        jPanel7.setBackground(lightBlue);
        jPanel8.setBackground(lightBlue);
        jPanel10.setBackground(lightBlue);
    }//GEN-LAST:event_btnTeacher1MouseClicked

    private void btnFinance1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinance1MouseClicked
        // TODO add your handling code here:
        DashboardPanel.setVisible(false);
        NoticePanel.setVisible(false);
        CalenderPanel.setVisible(false);
        DeptMsPanel.setVisible(false);
        StudentMsPanel.setVisible(false);
        AddTeacherPanel.setVisible(false);
        FinancePanel.setVisible(true);

        jPanel10.setBackground(Color.white);

        Color lightBlue = new Color(204, 204, 255);
        jPanel4.setBackground(lightBlue);
        jPanel5.setBackground(lightBlue);
        jPanel6.setBackground(lightBlue);
        jPanel7.setBackground(lightBlue);
        jPanel8.setBackground(lightBlue);
        jPanel9.setBackground(lightBlue);
    }//GEN-LAST:event_btnFinance1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new adminPage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTeacherPanel;
    private javax.swing.JPanel CalenderPanel;
    private javax.swing.JPanel DashboardPanel;
    private javax.swing.JPanel DeptMsPanel;
    private javax.swing.JPanel FinancePanel;
    private javax.swing.JPanel NoticePanel;
    private javax.swing.JPanel StudentMsPanel;
    private javax.swing.JLabel btnCalender1;
    private javax.swing.JLabel btnDashBoard1;
    private javax.swing.JLabel btnDept1;
    private javax.swing.JLabel btnFinance1;
    private javax.swing.JLabel btnNotice1;
    private javax.swing.JLabel btnStudent1;
    private javax.swing.JLabel btnTeacher1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
